# ============================================================
# PostgreSQL — Configuração com Hardening de Segurança
# FinCore Banking
# ============================================================

# CONEXÕES
max_connections            = 100
superuser_reserved_connections = 3

# AUTENTICAÇÃO
password_encryption = md5

# MEMÓRIA
shared_buffers             = 128MB
effective_cache_size       = 512MB
work_mem                   = 4MB
maintenance_work_mem       = 64MB

# SEGURANÇA — Timeouts
statement_timeout          = 30000
lock_timeout               = 10000
idle_in_transaction_session_timeout = 60000

# LOGGING DE SEGURANÇA
logging_collector          = on
log_directory              = 'pg_log'
log_filename               = 'postgresql-%Y-%m-%d.log'
log_rotation_age           = 1d
log_rotation_size          = 100MB
log_min_messages           = WARNING
log_min_error_statement    = ERROR
log_connections            = on
log_disconnections         = on
log_lock_waits             = on
log_checkpoints            = on
log_min_duration_statement = 1000

# PROTEÇÃO
authentication_timeout     = 60s

# WAL
wal_level                  = replica
fsync                      = on
synchronous_commit         = on
full_page_writes           = on

# VACUUM
autovacuum                 = on
autovacuum_max_workers     = 3